name: Check broken links

on:
  push:
    branches: [test/linkinator]
  pull_request:
    branches: [test/linkinator]
  schedule:
    - cron: "0 5 * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Dependencies
        run: |
          yarn install
      - name: Pull Docs
        run: |
          yarn sync-docs && git status
      - name: Run link check
        id: link-check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'
          config-file: '.github/mlc_config.json'
          folder-path: 'doc/docs/, doc/i18n/'
        continue-on-error: true
